name: user ci
on:
  workflow_dispatch
jobs:
  call-common:
    uses: thippareddyom/github-actions-reusable/.github/workflows/ci.yml@main
  # Build:
  #   runs-on: self-hosted
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v4
  #     - run: echo build
  # Test:
  #   runs-on: self-hosted
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v4
  #     - run: echo Test
  # Deploy:
  #   runs-on: self-hosted
  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v4
  #     - run: echo Deploy     
